insert into items(name,category_id,image,description,size,color,amount,price)
values ('t-shirt', 1, '61vbjJo8UJL._AC_SR1472,1840_.jpg', 'polo v-neck light t-shirt', 's', 'navy', 1, 100),
       ('t-shirt', 1, 'img_3.png', 'adidas t-shirt', 's', 'black', 1, 50),
       ('t-shirt', 1, 'img_2.png', 'adidas t-shirt', 'm', 'dark-green', 1, 50),
       ('t-shirt', 1, 'img_4.png', 'polo t-shirt', 's', 'beige', 1, 200),
       ('t-shirt', 1, 'img_5.png', 'polo t-shirt', 'l', 'navy', 1, 200),
       ('blouse', 1, '61asCyywEfL._AC_SR1472,1840_.jpg', 'calvin klein blouse', 'm', 'blue', 2, 150),
       ('blouse', 1, 'img_8.png', 'tommy blouse', 's', 'blue', 2, 150),
       ('blouse', 1, 'img_9.png', 'Ralph Lauren blouse', 'xs', 'blue', 2, 150),
       ('sneakers', 2, 'img_10.png', 'good shoes for spring', 'us8', 'black/white', 1, 200),
       ('t-shirt', 1, 'img_11.png', 'nike t-shirt', 'l', 'white', 1, 80),
       ('t-shirt', 1, 'img_12.png', 'puma t-shirt', 'xl', 'black', 1, 70),
       ('blouse', 1, 'img_13.png', 'floral blouse', 'm', 'pink', 3, 120),
       ('blouse', 1, 'img_14.png', 'ruffled blouse', 's', 'beige', 2, 90),
       ('sneakers', 2, 'img_15.png', 'casual sneakers', 'us8', 'green/white', 2, 180),
       ('t-shirt', 1, 'img_16.png', 'striped t-shirt', 'm', 'white', 1, 60),
       ('t-shirt', 1, 'img_17.png', 'graphic t-shirt', 's', 'white', 1, 70),
       ('blouse', 1, 'img_18.png', 'chiffon blouse', 'l', 'black', 2, 130),
       ('blouse', 1, 'img_19.png', 'off-shoulder blouse', 'xs', 'black', 3, 110),
       ('sneakers', 2, 'img_20.png', 'athletic sneakers', 'us9', 'white/gray', 1, 220),
       ('t-shirt', 1, 'img_21.png', 'plain t-shirt', 'm', 'gray', 1, 90),
       ('t-shirt', 1, 'img_22.png', 'vintage t-shirt', 'l', 'brown', 1, 100),
       ('sneakers', 2, 'img_23.png', 'canvas sneakers', 'us10', 'blue/white', 1, 180),
       ('sneakers', 2, 'img_24.png', 'new balance', 'us8', 'white', 2, 180),
       ('sneakers', 2, 'img_25.png', 'adidas running shoes', 'us8', 'blue', 2, 180),
       ('sneakers', 2, 'img_26.png', 'puma sneakers', 'us8', 'black', 2, 180),
       ('sneakers', 2, 'img_27.png', 'adidas sneakers', 'us8', 'pink', 2, 180),
       ('sneakers', 2, 'img_28.png', 'running outdoor', 'us8', 'gray', 2, 180);