insert into items(name,category_id,image,description,size,color,amount,price)
values ('t-shirt', 1, '61vbjJo8UJL._AC_SR1472,1840_.jpg', 'polo v-neck light t-shirt', 's', 'navy', 1, 100),
       ('t-shirt', 1, 'img_3.png', 'adidas t-shirt', 's', 'black', 1, 50),
       ('t-shirt', 1, 'img_2.png', 'adidas t-shirt', 'm', 'dark-green', 1, 50),
       ('t-shirt', 1, 'img_4.png', 'polo t-shirt', 's', 'beige', 1, 200),
       ('t-shirt', 1, 'img_5.png', 'polo t-shirt', 'l', 'navy', 1, 200),
       ('blouse', 1, '61asCyywEfL._AC_SR1472,1840_.jpg', 'calvin klein blouse', 'm', 'blue', 2, 150),
       ('blouse', 1, 'img_6.png', 'tommy blouse', 's', 'blue', 2, 150),
       ('blouse', 1, 'img_1.png', 'zara blouse', 'xs', 'blue', 2, 150),
       ('sneakers', 2, '71DtYlMSsfL._AC_SR1840,1472_.jpg', 'good shoes for spring', 'us7', 'black/white', 1, 200),
       ('t-shirt', 1, 'img_2.png', 'nike t-shirt', 'l', 'red', 1, 80),
       ('t-shirt', 1, 'img_3.png', 'puma t-shirt', 'xl', 'gray', 1, 70),
       ('blouse', 1, 'img_1.png', 'floral blouse', 'm', 'pink', 3, 120),
       ('blouse', 1, 'img_6.png', 'ruffled blouse', 's', 'white', 2, 90),
       ('sneakers', 2, 'img_7.png', 'casual sneakers', 'us8', 'green', 2, 180),
       ('t-shirt', 1, 'img_2.png', 'striped t-shirt', 'm', 'blue', 1, 60),
       ('t-shirt', 1, 'img_3.png', 'graphic t-shirt', 's', 'white', 1, 70),
       ('blouse', 1, 'img_1.png', 'chiffon blouse', 'l', 'purple', 2, 130),
       ('blouse', 1, 'img_1.png', 'off-shoulder blouse', 'xs', 'yellow', 3, 110),
       ('sneakers', 2, 'img_7.png', 'athletic sneakers', 'us9', 'pink', 1, 220),
       ('t-shirt', 1, 'img_4.png', 'plain t-shirt', 'm', 'gray', 1, 90),
       ('t-shirt', 1, 'img_5.png', 'vintage t-shirt', 'l', 'brown', 1, 100),
       ('blouse', 1, 'img_6.png', 'lace blouse', 's', 'ivory', 2, 140),
       ('blouse', 1, 'img_6.png', 'silk blouse', 'xs', 'silver', 3, 120),
       ('sneakers', 2, 'img_7.png', 'canvas sneakers', 'us10', 'blue/white', 1, 180);
